language: fr

pipeline:
- name: WhitespaceTokenizer
- name: LanguageModelFeaturizer
  model_name: bert
  model_weights: "rasa/LaBSE"

- name: DIETClassifier
  epochs: 200
  learning_rate: 0.001
  constrain_similarities: True


- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 200
  retrieval_intent: faq
- name: ResponseSelector
  epochs: 200
  retrieval_intent: chitchat





policies:
- name: MemoizationPolicy
- name: TEDPolicy
- name: RulePolicy
assistant_id: 20240111-173327-unproductive-redoubt
