language: fr

pipeline:
- name: WhitespaceTokenizer
- name: LanguageModelFeaturizer
  model_name: bert
  model_weights: "rasa/LaBSE"
- name: "DIETClassifier"
  epochs: 400
  learning_rate: 0.01
- name: ResponseSelector

policies:
- name: MemoizationPolicy
- name: TEDPolicy
- name: RulePolicy
assistant_id: 20240111-173327-unproductive-redoubt
