recipe: default.v1

language: fr
pipeline:
- name: SpacyNLP
  model: fr_core_news_md
- name: SpacyTokenizer
- name: LanguageModelFeaturizer
  model_name: bert
  model_weights: "rasa/LaBSE"
- name: DIETClassifier
  epochs: 200
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 200
  retrieval_intent: faq
- name: ResponseSelector
  epochs: 200
  retrieval_intent: chitchat

policies:
- name: MemoizationPolicy
- name: TEDPolicy
- name: RulePolicy

assistant_id: 20240118-140128-snowy-muffin