recipe: default.v1

language: "fr"

pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
  analyzer: "word"      # Utilisation d'une analyse de mot      # Utilisation des mots vides en français
  min_df: 3
- name: DIETClassifier
  epochs: 150
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  retrieval_intent: faq
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  retrieval_intent: faq1
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  retrieval_intent: faq2
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  retrieval_intent: faq3
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  retrieval_intent: faq4
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
  retrieval_intent: chitchat
- name: FallbackClassifier
  threshold: 0.7
  ambiguity_threshold: 0.1

policies:
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.7
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: true
- name: UnexpecTEDIntentPolicy
  max_history: 6
  epochs: 100
- name: TEDPolicy
  max_history: 6
  epochs: 100
  constrain_similarities: true
assistant_id: 20240220-163612-free-billboard
