recipe: default.v1

language: fr
pipeline:
- name: SpacyNLP
  model: fr_core_news_md
- name: SpacyTokenizer
- name: SpacyFeaturizer
  pooling: mean
- name: LexicalSyntacticFeaturizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 200
  constrain_similarities: True
- name: SpacyEntityExtractor
#- name: ResponseSelector
#  epochs: 300
#  retrieval_intent: faq
#- name: ResponseSelector
#  epochs: 300
#  retrieval_intent: chitchat
- name: FallbackClassifier
  threshold: 0.4
  ambiguity_threshold: 0.1

policies: 
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
- name: MemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: "action_default_fallback"
  #enable_fallback_prediction: True
- name: UnexpecTEDIntentPolicy
  max_history: 6
  epochs: 100
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
assistant_id: 20240109-121537-express-pod