name: Clean Dataset

on:
  push:
    branches:
      - spacy  # Replace 'main' with the name of your main branch

jobs:
  test:
    runs-on: ubuntu-latest  # You can choose the runner platform here

    steps:
      - name: Update packages
        run: sudo apt-get update && sudo apt-get upgrade -y

      - name: Install SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.9  # Replace '3.x' with your Python version #python3 -m spacy download fr_core_news_md

      - name: Install dependencies
        run: |
         pip3 install 'rasa[spacy]' 
         python3 -m spacy download fr_dep_news_trf
         python3 -m spacy download fr_core_news_sm
         python3 -m spacy download fr_core_news_md
         python3 -m spacy download fr_core_news_lg
         pip3 install transformers
         pip3 install pandas
         pip3 install openpyxl
        # pip3 install --upgrade rasa

      #- name: Use Node.js 16
       # uses: actions/setup-node@v3
        #with:
         # node-version: '20'  # Explicitly specify Node.js 16
    
      - name: create output folder
        run: mkdir -p gridresults

      #- name: Run NLU Tests with config_laBSE.yml
      #  run: | 
      #      rasa test nlu --config config/config_laBSE.yml \
      #      --cross-validation --runs 1 --folds 2 \
      #      --out gridresults/config-labse
        
      - name: Run NLU Tests with config-regex.yml
        run: |
            rasa test nlu --config REGEX/config1.yml \
            --cross-validation --runs 1 --folds 2 \
            --out gridresults/config1 
      - name : copy config 1
        run : cp REGEX/config1.yml gridresults/config1

      - name: Run NLU with regex2
        run: |
            rasa test nlu --config REGEX/config2.yml \
            --cross-validation --runs 1 --folds 2 \
            --out gridresults/config2
      - name : copy config 2
        run : cp REGEX/config2.yml gridresults/config2

      - name: Run NLU with CONFIG 3
        run: |
          rasa test nlu --config REGEX/config3.yml \
          --cross-validation --runs 1 --folds 2 \
          --out gridresults/config3

      - name : copy config 3
        run : cp REGEX/config3.yml gridresults/config3

      - name: Run NLU with count CONFIG4
        run: |
          rasa test nlu --config REGEX/config4.yml \
            --cross-validation --runs 1 --folds 2 \
            --out gridresults/config4

      - name : copy config 4
        run : cp REGEX/config4.yml gridresults/config4
        
      - name: Run NLU with count CONFIG5
        run: |
          rasa test nlu --config REGEX/config5.yml \
            --cross-validation --runs 1 --folds 2 \
            --out gridresults/config5


      - name : copy config 5
        run : cp REGEX/config5.yml gridresults/config5

      - name: Run NLU with count CONFIG6
        run: |
          rasa test nlu --config REGEX/config6.yml \
            --cross-validation --runs 1 --folds 2 \
            --out gridresults/config6

      - name : copy config 6
        run : cp REGEX/config6.yml gridresults/config6

      - name: Run NLU with count CONFIG7
        run: |
              rasa test nlu --config REGEX/config7.yml \
                --cross-validation --runs 1 --folds 2 \
                --out gridresults/config7

      #- name : copy config 7
      #  run : cp REGEX/config7.yml gridresults/config7

      #- name: Run NLU with count CONFIG8
      #  run: |
      #      rasa test nlu --config REGEX/config8.yml \
      #        --cross-validation --runs 1 --folds 2 \
      #        --out gridresults/config8

      #- name : copy config 8
      #  run : cp REGEX/config8.yml gridresults/config8

      #- name: extract reuslt
      #  run : python extract_result.py
      - uses: actions/upload-artifact@v3
        with:
          name: spacy_v2
          path: gridresults