name: Clean Dataset

on:
  push:
    branches:
      - master_fallback  # Replace 'main' with the name of your main branch

jobs:
  test:
    runs-on: ubuntu-latest  # You can choose the runner platform here

    steps:
      - name: Update packages
        run: sudo apt-get update && sudo apt-get upgrade -y

      - name: Install SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.9  # Replace '3.x' with your Python version

      - name: Install dependencies
        run: |
         pip3 install 'rasa[spacy]'
         python3 -m spacy download fr_core_news_md
         pip3 install transformers
        # pip3 install --upgrade rasa

      #- name: Use Node.js 16
       # uses: actions/setup-node@v3
        #with:
         # node-version: '20'  # Explicitly specify Node.js 16
    
      - name: create output folder
        run: mkdir -p gridresults

      #- name: Run NLU Tests with config_laBSE.yml
      #  run: | 
      #      rasa test nlu --config config/config_laBSE.yml \
      #      --cross-validation --runs 1 --folds 2 \
      #      --out gridresults/config-labse
        
      #- name: Run NLU Tests with config-regex.yml
      #  run: |
      #      rasa test nlu --config config/config-regex.yml \
      #      --cross-validation --runs 1 --folds 2 \
      #      --out gridresults/config-regex 
      - name: Run NLU with spacy
        run: |
            rasa test nlu --config config/config_spacy_and_bert \
            --cross-validation --runs 1  \
            --out gridresults/config-spacy_bert

      - uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: gridresults